name: Conan Request
author: Alexandr Timofeev <alexandr.p.timofeev@gmail.com>
description: An action to request an update of the recipe in the Conan Center Index.

inputs:
  token:
    description: GitHub token secret
    required: true
  packageName:
    description: The name of the package in the upstream repository
    required: false
  upstreamRepo:
    description: The upstream repository
    required: false
    default: "conan-center-index"
  upstreamOwner:
    description: GitHub token secret
    required: false
    default: "conan-io"

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "package"
  color: "blue"
